### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by shivanmodha** [SBCompSciClub/SBCompSciClub.github.io#2]
The website is currently configured with the default react favicon when it should have a default specialized icon.

**Comment by SethuSenthil** [comment]
React? I thought this website was developed using the Bootstrap framework, right?

**Comment by shivanmodha** [comment]
While bootstrap is the front end framework used, the bulk of the site (logic and interactivity) was created through the Javascript Library React and deployed to this repository. Bootstrap is the static CSS/JS library that makes the site aesthetic (like the now deprecated MDL), but the run time markdown compilation, component switch out, and URL routing is handled all through React.

**Comment by kevinsun-dev** [comment]
Alright, will create a nice favicon tomorrow.
